[project]
name = "ui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pathlib>=1.0.1",
    "streamlit>=1.45.1",
    "streamlit-autorefresh>=1.0.1",
]
