[project]
name = "smartr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.45.1",
    "streamlit-autorefresh>=1.0.1",
    "streamlit-webrtc>=0.62.4",
    "websocket-client>=1.8.0",
]
